sudo: required
services:
  - docker

before_install:
  - docker build -t trip00r/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true trip00r/docker-react npm run test -- --coverage