sudo: required
services:
  - docker

before_install:
  - docker build -t trip00r/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true trip00r/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-796543226828"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY